### ISSUE TITLE
Question about different models and GPU usage (i.e., VSSM, VSS, and VSSMD) 

### ISSUE THREAD

**Issue by gokulsrin** [MzeroMiko/VMamba#10]
Hi! Thank you all for making this amazing work public! It is really helpful!

I had a question about the different models/files. What is the difference between VSSM, VSS, and VSSMD? Are they the same thing or should I use one versus the other? 

Another question I had is about actually using the models. I'm loading the model like this: 
```
def load_model(): 
    model = VSS(depths=[2, 2, 9, 2], dims=96)
    model.head = nn.Sequential(
        nn.Linear(768, 1024, bias = True), 
        nn.ReLU(),
        nn.Dropout(p=0.5), 
        nn.Linear(1024, 1024, bias = True), 
        nn.ReLU(),
        nn.Dropout(p=0.5), 
        nn.Linear(1024, 1000, bias = True)
    )
    # model = torch.nn.DataParallel(model) #make parallel

    model.train()
    model = model.cuda()
    return model 
```
However, I find that when I run inference or attempt to train the model, it uses an absurd amount of GPU memory. I am using 512*512 pixel images, and I can only support a batch size of 16 given the configuration described. The model itself only takes 500 MB of VRAM, but each image takes around ~2 GB of VRAM. Am I doing something wrong?

**Comment by gokulsrin** [comment]
Some more information: I'm using a GPU with 32 GB VRAM. Surely, I should be able to have a larger batch size, no? I can do so with ResNet and ViT. Even without parallelization, I can run batch sizes of up to 64/128.

**Comment by MzeroMiko** [comment]
Than you for your attention. 
We use the model VSSM. The hyper-parameter depths=[2,2,9,2], dims=96 is exactly the standard of vssm_tiny. 
We have batch size 32 each card for classification with resolution 224x224, which cost 7000+MB gpu memories.  
We have batch size 2 and resolution 512x512 in upernet framework for ADE20k segmentation, which only cost 6000+MB GPU memories, even with extra big modules in upernet framework. see https://drive.google.com/file/d/17nh9_hdF9QQxyqj81U86HoGUnMxZQ4nN/view for details.
