### ISSUE TITLE
Could you please explan the last two lines of derivations?

### ISSUE THREAD

**Issue by lambdawill** [MzeroMiko/VMamba#100]
![图片](https://github.com/MzeroMiko/VMamba/assets/26055298/c2524cf3-7582-435e-9cc6-7f968d707d7b)
I am weak at math, so please give me detailed derivations if possible, thank you.

**Comment by MzeroMiko** [comment]
This shows that we can get the SSMScanOp in cuda code with math derivations.
The final line is just a repeat of the last second line. And the last second line means that we want to get the form of prefix-scan in calculation.
