### ISSUE TITLE
Question about backward() in CrossScan and CrossMerge

### ISSUE THREAD

**Issue by kangben258** [MzeroMiko/VMamba#101]
First of all, thank you for your outstanding work. While using VMamba for other downstream tasks, I encountered some issues. If I use the backward methods of CrossScan and CrossMerge in the code （not the CrossScanTriton）, my model fails to converge. However, when I use PyTorch's automatic backward method, the model converges normally. I would like to understand the significance of the backward methods of CrossScan and CrossMerge here. If it's for acceleration purposes, does it mean that if I don't need acceleration, I can use PyTorch's automatic backward method instead of the one used here?

**Comment by MzeroMiko** [comment]
Yes, you can use the automatic backward version, and theoretically they are the same. 

CrossScan and CrossMerge implemented with torch.autograd.Function is slightly faster. We tested the speed in `vmamba_check.py`, and shows:
```python
29.458091735839844 19.472640991210938 17.819852828979492 114.27430725097656 30.308349609375 20.641536712646484
```
The result is for the time-consumption of `auto backward for scan`, `manual backward for scan`, `triton scan`; `auto backward for merge`, `manual backward for merge`, `triton merge`. For more see `vmamba_check.py`.

**Comment by kangben258** [comment]
Thanks for your reply！
