### ISSUE TITLE
The pre-training problem?

### ISSUE THREAD

**Issue by 924973292** [MzeroMiko/VMamba#104]
<img width="1076" alt="截屏2024-03-24 13 00 41" src="https://github.com/MzeroMiko/VMamba/assets/89966785/866f8376-5611-4512-b8b1-02e2b7ed52ff">
I wonder why the first testing process will get a 100% acc?
And the second test looks normal?
This is the third epoch, every epoch will perform similar results, the first to be 100% 🥹

And could you please provide the structure of the ImageNet1k?
My structure is as follows:
ImageNet1k
--ILSVRC2012_validation
<img width="262" alt="截屏2024-03-24 14 36 32" src="https://github.com/MzeroMiko/VMamba/assets/89966785/6f77807a-3ee0-4225-b316-e0bbe01cc6eb">
--ILSVRC2012_train
<img width="259" alt="截屏2024-03-24 14 36 53" src="https://github.com/MzeroMiko/VMamba/assets/89966785/6f3ea918-9fbb-4b67-8516-585a2656e2e5">

Would this be OK?

**Comment by MzeroMiko** [comment]
I followed `swin-transformer`  to construct the data structure, which is very simple.

```bash
$ tree data
imagenet
├── train
│   ├── class1
│   │   ├── img1.jpeg
│   │   ├── img2.jpeg
│   │   └── ...
│   ├── class2
│   │   ├── img3.jpeg
│   │   └── ...
│   └── ...
└── val
    ├── class1
    │   ├── img4.jpeg
    │   ├── img5.jpeg
    │   └── ...
    ├── class2
    │   ├── img6.jpeg
    │   └── ...
    └── ...
```

**Comment by 924973292** [comment]
Thanks for your reply!
I followed your structure, now the training and testing precess become normal!
