### ISSUE TITLE
The FLOPs counting problem

### ISSUE THREAD

**Issue by 924973292** [MzeroMiko/VMamba#108]
Unsupported operator aten::mul encountered 132 time(s)
Unsupported operator aten::mul_ encountered 24 time(s)
Unsupported operator aten::add encountered 36 time(s)
Unsupported operator aten::gelu encountered 12 time(s)

When i am testing the flops of the model, i have these information on the terminal?
How to solve them?

**Comment by MzeroMiko** [comment]
You can just ignore it. 
we use flops counted by `fvcore`, in which [says](https://github.com/facebookresearch/fvcore/blob/main/fvcore/nn/jit_analysis.py#L27C1-L90C1) as below. So any thing like the operations below can be ignored. But other operations like `SelectiveScan` shall not be ignored, but to write an extra function to specifically count it.  (Be SENSITIVE in this case!)

For `add` and `mul`, these two operations do have slight flops, but are ignored in almost all repos.

```python

# Only ignore ops that are technically truly 0 flops:
# shape-manipulation ops, integer ops, memory copy ops
_IGNORED_OPS: Set[str] = {
    "aten::Int",
    "aten::ScalarImplicit",
    "aten::__and__",
    "aten::arange",
    "aten::bitwise_not",
    "aten::cat",
    "aten::chunk",
    "aten::clamp",
    "aten::clamp_",
    "aten::constant_pad_nd",
    "aten::contiguous",
    "aten::copy_",
    "aten::detach",
    "aten::dropout",
    "aten::empty",
    "aten::eq",
    "aten::expand",
    "aten::flatten",
    "aten::floor",
    "aten::floor_divide",
    "aten::full",
    "aten::full_like",
    "aten::gather",
    "aten::ge",
    "aten::gt",
    "aten::index",
    "aten::index_put_",
    "aten::masked_fill",
    "aten::max",
    "aten::narrow",
    "aten::new_empty",
    "aten::new_full",
    "aten::new_zeros",
    "aten::nonzero",
    "aten::ones",
    "aten::permute",
    "aten::relu",
    "aten::relu_",
    "aten::remainder",
    "aten::reshape",
    "aten::roll",
    "aten::select",
    "aten::size",
    "aten::slice",
    "aten::split",
    "aten::split_with_sizes",
    "aten::squeeze",
    "aten::stack",
    "aten::t",
    "aten::to",
    "aten::transpose",
    "aten::type_as",
    "aten::unbind",
    "aten::unsqueeze",
    "aten::unsqueeze_",
    "aten::view",
    "aten::zeros",
    "aten::zeros_like",
}

```

**Comment by 924973292** [comment]
Thanks for your quick reply!
You will make great work!

**Comment by 924973292** [comment]
The following submodules of the model were never called during the trace of the graph. They may be unused, or they were accessed by direct calls to .forward() or via other python methods. In the latter case they will have zeros for statistics, though their statistics will still contribute to their parent calling module:
ssm.SSM_b.dt_proj,
ssm.SSM_b.x_proj,
ssm.SSM_f.dt_proj, 
ssm.SSM_f.x_proj

Would these be incorrect to the final result?

**Comment by MzeroMiko** [comment]
In our cases, it does not matter, as we used their weights and bias rather than the modules themselves. But in other cases, it depends.

By the way, I remembered in my code, those modules have been created but deleted later in init function, how can you trace that?

And I do remember that there's no such things as `SSM_b` or `SSM_f`, is that code realy from my repo?

**Comment by 924973292** [comment]
I see!
In fact, i  make some adjustment to your code to see the bi-directional modeling, where the ssm_f/ ssm_b comes from.
I did not delete the module, instead directly apply self.dt_proj.weight, that may cause the problem.
And now I solve the problem!

**Comment by 924973292** [comment]
base.blocks.0.drop_path  is still here
Would drop_path is not used during testing?
Or with a prob it not being used, so the code will show it?

**Comment by MzeroMiko** [comment]
Yes, you are right.

In testing, droppath is automatically set to 0. See #70 for details.
