### ISSUE TITLE
Results of 1024 resolution

### ISSUE THREAD

**Issue by shawnricecake** [MzeroMiko/VMamba#11]
Is there any results for 1024x1024 resolution on ImageNet-1K?
or for segmentation / detection tasks.

Also, is there any latency / throughput comparison?

Look forward to your kind reply!
Shawn

**Comment by MzeroMiko** [comment]
We do not have 1024x1024 resolution for classification, except for the small experiment of scaling up image resolutions and test model performance without finetuning.
But the performance in detection is tested in images with mmcv.Resize(scale=(1333, 800)), the hyper-parameter "scale" of which, by the way, "If it is a float number, then the image will be rescaled by this factor, else if it is a tuple of 2 integers, then the image will  be rescaled as large as possible within the scale.(from mmdet.datasets.transforms)".
We hope this would help you.

**Comment by shawnricecake** [comment]
> We do not have 1024x1024 resolution for classification, except for the small experiment of scaling up image resolutions and test model performance without finetuning. But the performance in detection is tested in images with mmcv.Resize(scale=(1333, 800)), the hyper-parameter "scale" of which, by the way, "If it is a float number, then the image will be rescaled by this factor, else if it is a tuple of 2 integers, then the image will be rescaled as large as possible within the scale.(from mmdet.datasets.transforms)". We hope this would help you.

That helps, thank you
