### ISSUE TITLE
DDP Training

### ISSUE THREAD

**Issue by EasonXiao-888** [MzeroMiko/VMamba#115]
I want to use the DDP method for training, but when I turn on 2 machines with 5 gpus, `torch.cuda.set_device(rank)` reports an error `cuda error: invalid device ordinal`, while 2 machines with 4 gpus do not. I would like to ask why.

**Comment by lsmlyn** [comment]
I failed to train vmamba by DP, how to use it by DDP?

**Comment by EasonXiao-888** [comment]
@lsmlyn  I solve my issue when i change the code from `torch.cuda.set_device(rank)` to ` torch.cuda.set_device(rank % torch.cuda.device_count())` in the  classification/main.py

**Comment by lsmlyn** [comment]
> @lsmlyn I solve my issue when i change the code from `torch.cuda.set_device(rank)` to ` torch.cuda.set_device(rank % torch.cuda.device_count())` in the classification/main.py
Thank you! I'll try and see if it works on my issue.
