### ISSUE TITLE
causal_conv1d_cuda import error

### ISSUE THREAD

**Issue by shawnricecake** [MzeroMiko/VMamba#12]
```
 File "/home/sx/anaconda3/envs/sam/lib/python3.11/site-packages/mamba_ssm/__init__.py", line 3, in <module>
    from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
  File "/home/sx/anaconda3/envs/sam/lib/python3.11/site-packages/mamba_ssm/ops/selective_scan_interface.py", line 9, in <module>
    from causal_conv1d import causal_conv1d_fn
  File "/home/sx/anaconda3/envs/sam/lib/python3.11/site-packages/causal_conv1d/__init__.py", line 3, in <module>
    from causal_conv1d.causal_conv1d_interface import causal_conv1d_fn, causal_conv1d_update
  File "/home/sx/anaconda3/envs/sam/lib/python3.11/site-packages/causal_conv1d/causal_conv1d_interface.py", line 7, in <module>
    import causal_conv1d_cuda
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
```

How to download the following wheel file?

```
pip install causal_conv1d==1.0.0  # causal_conv1d-1.0.0+cu118torch1.13cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
pip install mamba_ssm==1.0.1  # mamba_ssm-1.0.1+cu118torch1.13cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
```

**Comment by MzeroMiko** [comment]
we downloaded causalconv1d package and mamba ssm package from their github repos. And we may provide those packages ourselves in the future.

**Comment by eclipse0922** [comment]
You do not need to install from the wheel file.
You can install from pip becasue they uploaded package already.
Or download the source code( `git clone ~~`) and run `pip install -e .` in each subdirectory.

**Comment by shawnricecake** [comment]
Update here,

I just solved this problem by git clone the repo from GitHub and use `pip install -e .`

Thanks
Shawn

> You do not need to install from the wheel file. You can install from pip becasue they uploaded package already. Or download the source code( `git clone ~~`) and run `pip install -e .` in each subdirectory.
