### ISSUE TITLE
about forwardtype

### ISSUE THREAD

**Issue by qiuzidian** [MzeroMiko/VMamba#127]
Is forwardtype=v4 currently the best? The latest configuration `classification/configs/vssm1/vssm_tiny_224_0327.yaml` sets forwardtype to "xv2aact". I don’t know the difference between them, could you explain it?

**Comment by MzeroMiko** [comment]
The `xv` series are still under development, so it is not recommended to use it.

Technically, in `forwardv2`, the `v4` (also called `v05`) version is the best.

**Comment by qiuzidian** [comment]
thank you
