### ISSUE TITLE
About to-dtype

### ISSUE THREAD

**Issue by LMMMEng** [MzeroMiko/VMamba#138]
Thank you for your wonderful work!

I notice that after the out-norm, the author converts the output to the same precision as the input. Is this to prevent loss=nan in the case of amp training?
https://github.com/MzeroMiko/VMamba/blob/fd943c728564539956eb8ba154b907f66268b04d/classification/models/vmamba.py#L532

**Comment by MzeroMiko** [comment]
Basically yes. 

I tried running the s6 in fp16 (which is the default setting when using torch.amp) and the loss got NaN after some epochs.

A straightforward solution to this is to disable torch.amp, but this will make the training even slower. So I put s6 in fp32 individually, and norm it to avoid overflow of fp16 and then convert it to fp16. That is what happened in v1 version of arxiv paper.

And in the v2 version, the design has been upgraded into input fp16 data into s6, and then output fp32, which is even faster.

**Comment by LMMMEng** [comment]
Thank you for your reply!
