### ISSUE TITLE
FORWARD_TYPES.get(forward_type, None) return NoneType

### ISSUE THREAD

**Issue by zichengpan** [MzeroMiko/VMamba#139]
Hi! Thanks for your great work. I try to reproduce your result of VMamba-B using the evaluation command. The config file and checkpoint model are all correctly set. However, I encounter the following error. Is there anything wrong with my configuration?

    y = self.forward_core(x)
TypeError: 'NoneType' object is not callable

**Comment by MzeroMiko** [comment]
May I ask what config you are using? 
I've checked `configs/vssm1/vssm_base_224.yaml` and `configs/vssm01/vssm_base_224_aav1.yaml` and `configs/vssm/vssm_base_224.yaml` now, they all work well.

**Comment by zichengpan** [comment]
Oh it works now. I am using the config file given in the classification table last row. Seems that the SSM_FORWARDTYPE should be "v3noz" instead of "v3_noz". Thanks for your checking!
