### ISSUE TITLE
'MMSEG_VSSM is not in the mmseg::model registry.

### ISSUE THREAD

**Issue by xwmaxwma** [MzeroMiko/VMamba#14]
想问下出现这个问题什么原因，是还要在mmseg里的init函数里手动导入'MMSEG_VSSM类吗
![image](https://github.com/MzeroMiko/VMamba/assets/96612872/e545e27c-c22a-4f64-b65b-f47e8cde88cd)

**Comment by abelny56** [comment]
@xwmaxwma Did you solve it? I met the same problem
