### ISSUE TITLE
tiny model ckpt not match the model weights

### ISSUE THREAD

**Issue by shengyu27** [MzeroMiko/VMamba#148]
When I use the tiny model and find that some of the shapes in the model do not match the shape of the model
this is the ckpt:vssm_tiny_0230_ckpt_epoch_262.pth
![model](https://github.com/MzeroMiko/VMamba/assets/101924320/f7b8c7ab-5aea-4307-a363-41acb75c662a)
this is the model weights:
![ckpt](https://github.com/MzeroMiko/VMamba/assets/101924320/447ae3e3-df56-4bc6-bc08-8494518f1a10)
this is the model config:
![model param](https://github.com/MzeroMiko/VMamba/assets/101924320/e26e085a-65d8-4625-a03a-025554fa1ccc)

**Comment by MzeroMiko** [comment]
So where do you get that config file?

**Comment by shengyu27** [comment]
> So where do you get that config file?

from the readme table 'Classification on ImageNet-1K with VMambav2'
https://github.com/MzeroMiko/VMamba/blob/main/classification/configs/vssm/vmambav2_tiny_224.yaml

**Comment by MzeroMiko** [comment]
It seems that the hyper-parameter in the picture your provide mismatch what in `https://github.com/MzeroMiko/VMamba/blob/main/classification/configs/vssm/vmambav2_tiny_224.yaml`, e.g.  `ssm_d_state=16` in your fig, but `SSM_D_STATE=1` in the yaml config. Fix that and try again.

**Comment by shengyu27** [comment]
> It seems that the hyper-parameter in the picture your provide mismatch what in `https://github.com/MzeroMiko/VMamba/blob/main/classification/configs/vssm/vmambav2_tiny_224.yaml`, e.g. `ssm_d_state=16` in your fig, but `SSM_D_STATE=1` in the yaml config. Fix that and try again.

oh, this is my mistake, thanks.
