### ISSUE TITLE
2D Selective Scan

### ISSUE THREAD

**Issue by shawnricecake** [MzeroMiko/VMamba#15]
Hi,

I would like to know what you mean by `K=4` in the selective scan part:
https://github.com/MzeroMiko/VMamba/blob/282a370ec015122fffb4961b8446eb9071377c28/classification/models/vmamba/vmamba.py#L347

Because, in my opinion, I think that, in the selective scan, the shape of input B and C might be 3 (while in your code is `(b, k, d_state, l)`)

I understand that the K=4 might be related to the 2D selective scan, and is that OK for this 4d tensor as the input of the function of selective scan in `mamba_ssm` package?

Looking forward to your reply.

Thanks
Shawn

**Comment by shawnricecake** [comment]
By the way,

For simplification, can I just process the 4 images in `xs` one by one to get the y1, y2, y3, y4?

**Comment by MzeroMiko** [comment]
K=4 means that we scan through 4 directions, but not the dimension of input tensor (which is hidden in d_model). mamba_ssm support group s6 forward and backward, and even the input is in 3d-tensor, it would change it to 4d first (refer https://github.com/state-spaces/mamba/blob/main/mamba_ssm/ops/selective_scan_interface.py ). 
You can sequentially process 4 x in different directions to get y1,y2,y3,y4, though it will be slower.

**Comment by shawnricecake** [comment]
Hi, is there any ablation study for this 2D selective scan? How about the performance of the model on imagenet without 2D selective scan?

**Comment by MzeroMiko** [comment]
We have not done any ablation studies yet. But we planned many, some of them have been implemented and are lining up for machine available.

**Comment by shawnricecake** [comment]
Hi, can you help explain the equation 2 in paper? How can I get the h0 at the initial? and what means x0, x1, x2, ..., xL?

**Comment by MzeroMiko** [comment]
Equation 2 shows how to discretize the original ODE. The procedure is basically the same with Mamba., where you may find detailed information.
h0 is initialized in `selective_scan_cuda.fwd` and `selective_scan_cuda.bwd`, which is all 0.
x0, ... xL means the vector in the input X (shape (B, G * D, L) G means groups, G=4 ), and the shape of xi is (B, G * D).

**Comment by shawnricecake** [comment]
> Equation 2 shows how to discretize the original ODE. The procedure is basically the same with Mamba., where you may find detailed information. h0 is initialized in `selective_scan_cuda.fwd` and `selective_scan_cuda.bwd`, which is all 0. x0, ... xL means the vector in the input X (shape (B, G * D, L) G means groups, G=4 ), and the shape of xi is (B, G * D).

thanks, that helps
