### ISSUE TITLE
ModuleNotFoundError: No module named 'model'

### ISSUE THREAD

**Issue by jiaweichaojwc** [MzeroMiko/VMamba#154]
![image](https://github.com/MzeroMiko/VMamba/assets/113352745/0e9f815c-c312-44d1-96d0-ed697ff780a9)
When I perform semantic segmentation,  I encounter a ModuleNotFoundError: No module named 'model'. I don't know where the problem lies. Can you provide some help? Thank you.

**Comment by nowander** [comment]
how do you solve this problem?

**Comment by jiaweichaojwc** [comment]
![image](https://github.com/MzeroMiko/VMamba/assets/113352745/1a8fa3a3-e235-4f77-962d-41608d78a8d0)
针对这个问题，请在tools/train.py里面加入如图的代码，即可解决

**Comment by jiaweichaojwc** [comment]
![image](https://github.com/MzeroMiko/VMamba/assets/113352745/1a8fa3a3-e235-4f77-962d-41608d78a8d0)
针对这个问题，请在tools/train.py里面加入如图的代码，即可解决
