### ISSUE TITLE
NameError: name 'selective_scan_cuda_core' is not defined

### ISSUE THREAD

**Issue by jiaweichaojwc** [MzeroMiko/VMamba#156]
当我安装cd kernels/selective_scan && pip install .出现了问题，我直接安装mamba_ssm-1.2.0.post1+cu118torch1.13cxx11abiFALSE-cp38-cp38-linux_x86_64，企图用mamba代替cd kernels/selective_scan && pip install .，结果出现了下面的错误
When I tried to install cd kernels/selective_scan && pip install ., I encountered an issue. I then attempted to directly install mamba_ssm-1.2.0.post1+cu118torch1.13cxx11abiFALSE-cp38-cp38-linux_x86_64 in place of cd kernels/selective_scan && pip install ., but I received the following error.
![image](https://github.com/MzeroMiko/VMamba/assets/113352745/71f81248-f228-413d-8d3d-112baa372b15)

**Comment by dragonBrother1** [comment]
兄弟，现在解决了吗？
