### ISSUE TITLE
training results

### ISSUE THREAD

**Issue by JAYCHOU2020** [MzeroMiko/VMamba#158]
Hi, thank you for your work while I was training at 4090 Single card, raining isic18 with the pretraining model pre_trained_weights/vssmsmall_dp03_ckpt_epoch_238.pth could not get the miou result of 81.35 in the paper.Only 0.793 miou

**Comment by MzeroMiko** [comment]
Where did you get the miou of 81.35, I checked the paper, and did not find that number.

**Comment by JAYCHOU2020** [comment]
> Where did you get the miou of 81.35, I checked the paper, and did not find that number.

![image](https://github.com/MzeroMiko/VMamba/assets/62323435/5944fbb9-5785-477d-b013-75263894990e)
vmamba v1
