### ISSUE TITLE
Vmamba's inference speed

### ISSUE THREAD

**Issue by moliwei2019** [MzeroMiko/VMamba#16]
Thanks for this incredible work! I want to know what is the inference speed of Vmamba and can Vmamba be accelerated using tensorrt?

**Comment by MzeroMiko** [comment]
Thank you for your attention. We think VMamba can be accelerated by TensorRT. But the speed bottle neck lies in selective scan, and we do not know whether it can be accelerated or not. In one block, as we observed, selective scan forward and backward takes 80%+ of the training time. The thoughput in 224x224 images in V100 is not that good: 200+for tiny, and ~100 for base. We think the thoughput may be relatively higher in larger resolutions compared to quadratic-complexity models like ViT.

**Comment by moliwei2019** [comment]
Thanks for your reply！
