### ISSUE TITLE
The differences between selective_scan_fn_v1 and selective_scan_fn

### ISSUE THREAD

**Issue by OliverHxh** [MzeroMiko/VMamba#17]
Hi authors, thanks for your great work. 

I just noticed your recent update on selective_scan_fn_v1. What are the differences compared to the original selective_scan_fn? Will it be faster?

Thanks.

**Comment by MzeroMiko** [comment]
It is released mainly to make setting up environment easier. In selective scan fn v1, we delete some features that we do not need (and will loosen some restricts like some weight must be in float in the future, which will make sleective scan faster but less precise). We have coarsely tested the speed with torch.profile, and find v1 a little bit faster (<10% in forward + backward).

**Comment by OliverHxh** [comment]
Thanks for your quick reply.
