### ISSUE TITLE
To understand the code

### ISSUE THREAD

**Issue by huansu** [MzeroMiko/VMamba#18]
Hello!
I'm trying to read the paper with code, but I have some questions in 
`classification/models/vmamba/vmamba.py` 
```
class SS2D()
    ......
    def forward(self, x: torch.Tensor, **kwargs):
        B, H, W, C = x.shape

        xz = self.in_proj(x)
        x, z = xz.chunk(2, dim=-1) # (b, h, w, d)

        x = x.permute(0, 3, 1, 2).contiguous()
        x = self.act(self.conv2d(x)) # (b, d, h, w)
        y1, y2, y3, y4 = self.forward_core(x)
        assert y1.dtype == torch.float32
        y = y1 + y2 + y3 + y4
        y = torch.transpose(y, dim0=1, dim1=2).contiguous().view(B, H, W, -1)
        y = self.out_norm(y)
        y = y * F.silu(z)
        out = self.out_proj(y)
        if self.dropout is not None:
            out = self.dropout(out)
        return out
```
**1.** x seems a four dimensional tensor, but self.in_proj is nn.Linear(). Could nn.Linear() receive a four dimensional tensor?
**2.** If x isn't a four dimensional tensor, how could self.conv2d()  process the data?
I look forward to hearing from you.
Cheers！

**Comment by MzeroMiko** [comment]
Q1: linear receives tensors with any shape if and only if the last dimension matches.
Q2: Conv2D means to process convolution in the last 2 dimensions and linear in the second dimension, all other dimensions needs to be permuted and reshaped into the first dimension.

**Comment by huansu** [comment]
@MzeroMiko 
Hello!
Thanks for your quickly reply. I have solved this question. 
Cheers!
