### ISSUE TITLE
Problems when opening config.py using yaml

### ISSUE THREAD

**Issue by Mahaha613** [MzeroMiko/VMamba#180]
In config.py, when reading using "yaml_cfg = yaml.load(f, Loader=yaml.FullLoader)", an error occurs:“yaml.parser.ParserError: expected 'document start', but found 'scalar'“. I found that this error will appear at the beginning of the next line of each line of comments. When I delete all the comments, "yaml.scanner.ScannerError: mapping values are not allowed here" will appear. The error location is in config.py the end of the definition of the first function(_update_config_from_file), that is, the position after ":". By the way, my yaml version is 5.1

**Comment by wbbmm** [comment]
Have you solved it yet?please

**Comment by wbbmm** [comment]
I'm having this problem too.
