### ISSUE TITLE
 Inquiry about SS2D Module: Clarification on d_state and dt_rank

### ISSUE THREAD

**Issue by invokeG** [MzeroMiko/VMamba#19]
Hi, authors, thanks for your great work. It's been incredibly insightful, and your contributions are invaluable.

I've been exploring the `SS2D` module in the codebase and have come across the parameters `d_state` and `dt_rank`. While I understand their roles in the module, I was hoping to gain more clarity on their specific meanings and significance within the context of the model.

Additionally, I am curious to know if the initialization of these parameters is closely tied to the patch block or if there are other considerations involved.

Thank you in advance for your time and assistance.

**Comment by MzeroMiko** [comment]
Thank you for your attention. 
We inherit the usage of`d_inner`,  `d_state` and `dt_rank`  from mamba.  `d_inner` means the dimension the input has inside SSM. `d_state` means the dimension of state parameters the SSM has. And the parameter A is in shape `(d_inner, d_state)`, B and C are in shape `(batch, d_state, length)`.
`dt_rank` means the effective dimensions (or the `rank`) \delta t has. You can see in the code that `dt` is firstly squeezed from `d_inner` to `dt_rank`, and then expand to `d_inner` again.

**Comment by invokeG** [comment]
Thank you so much for your prompt and detailed response.
