### ISSUE TITLE
Details About ERF Visualization

### ISSUE THREAD

**Issue by lcxrocks** [MzeroMiko/VMamba#196]
@MzeroMiko Thank you for your outstanding work and generous open-source contributions! I have a question regarding the use of `RandomSampler` when drawing ERFs for each feature extraction backbone:
https://github.com/MzeroMiko/VMamba/blob/c07d2ea1322061cd52a505fdae735c91346a5d65/analyze/utils.py#L317
Doesn't this mean that each heatmap represents the average result of several **different** image batches? Or is this not a significant concern because each batch contains 50 images, which is sufficient to mitigate any bias? Thank you!

**Comment by MzeroMiko** [comment]
Yes  It is the average ERF for 50 images. 
We adopted this code from [RepLKNet](https://github.com/DingXiaoH/RepLKNet-pytorch/tree/main/erf). You may refer to that for more information.

**Comment by lcxrocks** [comment]
Thank you very much!
