### ISSUE TITLE
vssm和vssm1？

### ISSUE THREAD

**Issue by uniPTG** [MzeroMiko/VMamba#220]
请问项目文件夹里面vssm和vssm1有什么区别？我看您的readme.md里面语义分割使用的config文件是vssm1里面的，但我在复现的时候使用vssm1文件夹里的会报错。反而使用vssm文件夹里面的能跑出来结果，但结果很差。

**Comment by MzeroMiko** [comment]
vssm refers to the vanilla version of VMamba, while the vssm1 is the VMamba with s2l5, s1l8,... For details you can refer to the arxiv paper.
