### ISSUE TITLE
Error,when I run the vmamba

### ISSUE THREAD

**Issue by funjq** [MzeroMiko/VMamba#23]
Hi! Thanks for your great work.I cannot use the module correctly.
![Snipaste_2024-01-30_16-45-20](https://github.com/MzeroMiko/VMamba/assets/77264204/a33dd19f-e203-4cf9-bce9-e5e84a478462)
![Snipaste_2024-01-30_16-45-48](https://github.com/MzeroMiko/VMamba/assets/77264204/03f9ac4b-4e06-4605-87dc-8b997fe3943c)

**Comment by MzeroMiko** [comment]
This function is written to check whether the new version of code aligns with the very previous one.  So this function makes no sense if you only want to train or infer the model in the current version.
By the way, `check_vssm1_equals_vssm` is to check the alignment between the code of `main` branch and `20240128` branch.

**Comment by funjq** [comment]
Thank you very much!
