### ISSUE TITLE
FLOPs

### ISSUE THREAD

**Issue by DuHao55** [MzeroMiko/VMamba#235]
Why is there a huge difference between the FLOPs (Swin-T for table4) that I calculated with mmsegmentaiton get_flops.py(torch1.12）and your paper? What is causing the discrepancy? Can you share what tool was used to calculate the FLOPs for each model in table4?

![image](https://github.com/MzeroMiko/VMamba/assets/117566234/5d8b751b-a1f6-4696-b123-5da15ee7836d)

**Comment by MzeroMiko** [comment]
What table is that when you refer to table-4? In our newly released arxiv paper, table-4 is ` Architectural overview of the VMamba series.` in the appendix.

**Comment by DuHao55** [comment]
Sorry, in your latest paper, it is table 9 of the appendix. why the parameters and FLOPs I calculated with mmsegmentation (torch1.12) are so different from your results, I would like to know why.
![image](https://github.com/MzeroMiko/VMamba/assets/117566234/f4c2e267-0e76-492c-8e84-ab4a41e70d93)

**Comment by MzeroMiko** [comment]
I see. I suppose that the performances of swin-t you tested are also worse than the results in table-9 in our arxiv paper.

There are two reasons may contribute to this:

1. the window size of swin we used in this table is scaled, which is equals to the resolution divided by 32. (If you check the config files in original swin repo, you can also find that design.) But in mmpretrain (or mmdet and mmseg), raising the image-size will not directly leads to the window-size scaling. 
![image](https://github.com/MzeroMiko/VMamba/assets/45236610/1131ff45-d6f1-4eda-8523-24d3161e22c8)
 
2. fvcore do not support `torch.nn.functional.scaled_dot_product_attention`, thus if this function is used when calculating flops, you need to replace it by the naive implementation of scaled-dot-product-attention.

The code in https://github.com/MzeroMiko/VMamba/blob/546c58911f5b159aea8bac36648bb712f1861ccb/analyze/tp.py#L58 did take those two factors into account, you can easily test the flops and throughput with it.

**Comment by MzeroMiko** [comment]
more specifically is 

https://github.com/MzeroMiko/VMamba/blob/546c58911f5b159aea8bac36648bb712f1861ccb/analyze/utils.py#L554

and 

https://github.com/MzeroMiko/VMamba/blob/546c58911f5b159aea8bac36648bb712f1861ccb/analyze/utils.py#L1505

**Comment by DuHao55** [comment]
Thanks for the reply, I'll try again.
