### ISSUE TITLE
语义分割pretrained

### ISSUE THREAD

**Issue by uniPTG** [MzeroMiko/VMamba#236]
![config](https://github.com/MzeroMiko/VMamba/assets/125844096/60c3d183-116b-4737-a460-5b93e17b21e2)
请问这里的pretrained=""为空，需要补上吗？因为我直接使用这个配置文件训练结果和您的结果差了非常多。

**Comment by MzeroMiko** [comment]
Yes. You should replace "" with the corresponding pretrained model checkpoint with classification.

**Comment by uniPTG** [comment]
thanks！
