### ISSUE TITLE
Question about grad_norm

### ISSUE THREAD

**Issue by syf-fgnb** [MzeroMiko/VMamba#252]
Hi 

Thanks for your excellent work. When I train the model, I always find grad_norm is something like "grad_norm xx.xxxx (inf)" but the loss is normal. Just want to know if it is a bad signal for training? Because I checked the log you provide, it also contains lots of "grad_norm xx.xxxx (inf)" items for grad_norm.

**Comment by MzeroMiko** [comment]
Yes it is really a signal，which indicates that the gradient is quite big, but is also common in many training cases. 

You can ignore it if the inf can be corrected in later training (the loss scale increases back progressively). But when you find that even the loss scale keeps reducing，the inf would not disappear，you may need to think about the robustness of you design carefully.
