### ISSUE TITLE
Max DSTATE in Selective Scan

### ISSUE THREAD

**Issue by Maitreyapatel** [MzeroMiko/VMamba#28]
Hello,
Great work and thanks for open-sourcing!

If we keep the `d_model>256` in SS2D, then it throws the error as the max DSTATE is set to 256.
   
https://github.com/MzeroMiko/VMamba/blob/fe841ae56fa601d0cca8747f4306faded4b389ba/selective_scan/csrc/selective_scan/selective_scan.cpp#L11

If possible, I wanted to learn more about this. If we want to increase this limit then will it cause unexpected issues?

Looking forward to your reply.

Thanks!

**Comment by MzeroMiko** [comment]
Thank you for your attention.
By saying `d_model > 256`, you mean `d_state > 256`, right?
In my understanding, the MAX_STATE is quite related to the shared memory that your GPU has per single thread block. For example, A100's is 163KB,  V100's is 49KB, 4090's is 128KB, as far as I know. You can refer to NVIDIA's  website for accurate numbers. Meanwhile, the bigger the MAX_STATE is, the more shared memory we may used, and the more [static shared memory](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#device-side-kernel-launch) we should [prepared](https://github.com/MzeroMiko/VMamba/blob/fe841ae56fa601d0cca8747f4306faded4b389ba/selective_scan/csrc/selective_scan/selective_scan_fwd_kernel.cuh#L220) .
To conclude, if you are sure that your gpu is capable with larger share memory, fell free to increase that, though in our cases, we only use the size of `nrows=4` * `d_state=16` = 64😂.

**Comment by Maitreyapatel** [comment]
Thanks for the info! This clarifies many of my questions.

**Comment by Dragon2938734** [comment]
> Hello, Great work and thanks for open-sourcing!
> 
> If we keep the `d_model>256` in SS2D, then it throws the error as the max DSTATE is set to 256.
> 
> https://github.com/MzeroMiko/VMamba/blob/fe841ae56fa601d0cca8747f4306faded4b389ba/selective_scan/csrc/selective_scan/selective_scan.cpp#L11
> 
> If possible, I wanted to learn more about this. If we want to increase this limit then will it cause unexpected issues?
> 
> Looking forward to your reply.
> 
> Thanks!

hi，i also want to increase the dim, shall i just modify the MAX_DSTATE 256 -> MAX_DSTATE 512 ok ? Is there anything else should i to modify?

looking forward to your reply.

thank you!

**Comment by MzeroMiko** [comment]
It may be ok if it works fine on your device. The limitation is quite related to the device you use, especially the size of shared memory.
