### ISSUE TITLE
Can not import selective_scan_cuda_oflex. This affects speed.

### ISSUE THREAD

**Issue by 180123** [MzeroMiko/VMamba#291]
Hello, this is a great job! I am now using vmamba as backbone on other models, but I get the following warning message, Can not import selective_scan_cuda_oflex. This affects speed. So what should I do and expect your reply

**Comment by 180123** [comment]
> Hello, this is a great job! I am now using vmamba as backbone on other models, but I get the following warning message, Can not import selective_scan_cuda_oflex. This affects speed. So what should I do and expect your r

**Comment by 180123** [comment]
This issue has been resolved

**Comment by zzc81824130** [comment]
> 此问题已解决
hello！i have meet the same problem，could you please tell me your way to fit this problem?

**Comment by 180123** [comment]
> > 此问题已解决
> > hello！i have meet the same problem，could you please tell me your way to fit this problem?

hello！I just reconfigured the environment, and hope it was helpful!

**Comment by BaophanN** [comment]
Excuse me, can you please explain in more detail what exactly you have done to resolve this issue. I have the same problem and it led to a bug that made training time go up to 245 days. I install selective_scan sucessfully following the instruction but still the problem prevails. Thank you

**Comment by 180123** [comment]
> Excuse me, can you please explain in more detail what exactly you have done to resolve this issue. I have the same problem and it led to a bug that made training time go up to 245 days. I install selective_scan sucessfully following the instruction but still the problem prevails. Thank you

Oh, my God！ I'm sorry to hear that. In my opinion you should choose to install the environment requirements provided by the author and then increase them accordingly. If you get a 245-day run time, I'm guessing there's something wrong with your environment.

**Comment by BaophanN** [comment]
I use framework mmcv v1.5.2 cuda 11.1 and pytorch 1.9, python 3.8. However, selective scan did not work on cuda 11.1 so there is no optimization either.

**Comment by 180123** [comment]
> I use framework mmcv v1.5.2 cuda 11.1 and pytorch 1.9, python 3.8. However, selective scan did not work on cuda 11.1 so there is no optimization either.

It is recommended that you upgrade the CUDA version and install the environment strictly according to the author's requirements.txt.

**Comment by 1666178607** [comment]
> 对不起，您能否更详细地解释一下您究竟做了什么来解决这个问题。我有同样的问题，它导致了一个错误，使训练时间上升到 245 天。我按照说明成功安装了selective_scan但问题仍然存在。谢谢

你弄好了吗，我和你问题好像一样都200多天有这个错误

**Comment by xiaoyuejin645-max** [comment]
请问你们用的什么显卡配置，我想将vmamba用到自己的任务中训练时间长达了105天，selective_scan_cuda_oflex是可以成功导入的但我不知道问题在哪里
