### ISSUE TITLE
Vmamba和Swin-Transformer相比的显存大小问题

### ISSUE THREAD

**Issue by xinpuliu** [MzeroMiko/VMamba#303]
首先感谢您们开源了这么好的工作，在实验中我发现，在相同计算量参数量配置下（例如tiny），Vmamba（最新版）仍比Swin-Transformer多占不少显存，请问这是正常的吗？还是我配置错误？

**Comment by MzeroMiko** [comment]
Due to the weaker support of hardware, VMamba do consume more device memory than swin-transformer in traning. But the difference is not that huge.  

![image](https://github.com/user-attachments/assets/5fefda86-47b3-4705-96ad-cf2661a44ce5)

**Comment by xinpuliu** [comment]
感谢您的快速回复~
