### ISSUE TITLE
when I train the detection model.

### ISSUE THREAD

**Issue by yuhua666** [MzeroMiko/VMamba#33]
import model
ModuleNotFoundError: No module named 'model'

**Comment by yuhua666** [comment]
ImportError: /root/miniconda3/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl

**Comment by jiaweichaojwc** [comment]
@yuhua666 当我跑分割数据集的时候也出现了这个问题，请问您解决了吗？谢谢
    import model
ModuleNotFoundError: No module named 'model'

**Comment by JaggerGu** [comment]
"import model" is written in the train.py and test.py, the program can't find this function
