### ISSUE TITLE
关于ssm_d_state

### ISSUE THREAD

**Issue by KLKb7** [MzeroMiko/VMamba#330]
![ssm_d_state](https://github.com/user-attachments/assets/e5c6e425-8691-4ccd-9b28-6b2bba94631f)Thank you for your outstanding work! Setting all the model parameters ssm_d_state to 1, isn't that a bit too aggressive for state compression? It should have a significant impact on the model's performance. Could you please share your thoughts on how you decided on these parameter settings?

**Comment by MzeroMiko** [comment]
I set the d_state = 1 for the consideration of speed. With poorer support of hardware for selective-scan, the speed can be really a problem. 

Also, in the ablation study in appendix, we found that when d_state is small, the impact of d_state on the model' performance is not that significant.
