### ISSUE TITLE
RuntimeError:Unknown layout

### ISSUE THREAD

**Issue by ElliottZhen** [MzeroMiko/VMamba#342]
你好，非常棒的工作，想请教您一些问题：
我尝试使用VMamba的一个VSSBlock用作我的下游任务，
我尝试了cuda11.8 torch2.2.0，2.2.1，也尝试了cuda12.1的对应版本
均会出现RuntimeError:Unknown layout
错误定位在csms6s.py的SelectiveScanCuda类的oflex部分，当我把SS2Dv2的selective_scan_backend由None改为torch，代码正常运行，但是速度特别慢，请问你知道怎么解决吗？
@MzeroMiko

**Comment by tiantian0426** [comment]
请问一下是需要将环境重新配置，然后在cd kernels/selective_scan 之后不运行pip install . 改为运行 python setup.py build & python setup.py install吗？另外请问下您的gcc、cuda与setuptools的版本，我的 GCC 版本为 7.3.1，CUDA 版本为 11.8，setuptools 版本是 80.9.0，Python 版本是 3.10，torch版本为2.2.0，现在遇到了RuntimeError: Unknown layout的问题
