### ISSUE TITLE
What's the meaning of nrows in the function and if we set it bigger, what would happen?

### ISSUE THREAD

**Issue by 924973292** [MzeroMiko/VMamba#36]

**Comment by MzeroMiko** [comment]
`nrows` means how many dims one thread process. 

In `selective scan`, we have `batch_size * d_inner // nrows` blocks, and in each block, we have N (typically 128) threads working on a chunk (`chunk size` = num_threads * num_items_per_threads) of the sequential data with length of `seq_len`, looping until all the data have finished.

In one thread, in one loop, we need to deal with `num_items_per_threads * d_state * nrows` groups of scalars. 
for details see `selective_scan/csrc/selective_scan/selective_scan_fwd_kernel.cuh` and `selective_scan/csrc/selective scan/selective_scan_bwd_kernel.cuh`.

Note that the `stream multiprosessor` in one gpu is not infinite (typically ~100, which is much smaller than the number of blocks we need), and scheduling streams also takes time. So `nrow` is used to balance the burden of `the number of blocks to process` and `the number of data one thread should process`.

However, `bigger nrow support` takes more time compling, so we only support `forward nrows=1,2,4; backward nrows = 1,2,4`.

Finally, will bigger nrow brings faster speed? it remains a question.
