### ISSUE TITLE
Weights for VMamba-B for ImageNet classification

### ISSUE THREAD

**Issue by ionut-grigore99** [MzeroMiko/VMamba#37]
Thanks for your excellent code! When do you plan to provide pretrained checkpoints for VMamba-B for classification on ImageNet?

**Comment by MzeroMiko** [comment]
Thank you for reminding me. I have released the logs and checkpoints now. If you have any questions in using that, do not hesitate to contact me, and I' try to fix as soon as possible.

**Comment by GZ-YourZY** [comment]
> 谢谢你提醒我。我现在已经发布了日志和检查点。如果您在使用过程中遇到任何问题，请随时与我联系，我会尽力尽快解决。

请问何时公开分割任务的检查点，我试图点击ckpt下载权重但没有反应

**Comment by MzeroMiko** [comment]
@GZ-YourZY we have released all the checkpoints for version 0, you can find the links in readme.
