### ISSUE TITLE
training speed

### ISSUE THREAD

**Issue by oszn** [MzeroMiko/VMamba#4]
add SS2D module, training speed become slowly,The time consumed is 40% longer than that of CNN. Is this normal?

**Comment by sunsmarterjie** [comment]
It's expected for us to be slower than CNN models. VMamba is quicker than attention-based models mainly in high resolutions, like Vim. However, using the same computing power, the "for loop" implementation of ss2d makes it slower. We're working on improving this and plan to release a new version if we success.

**Comment by sunsmarterjie** [comment]
It's expected for us to be slower than CNN models. VMamba is quicker than attention-based models mainly in high resolutions, like Vim. However, using the same flops, the "for loop" implementation of ss2d makes it slower. We're working on improving this and plan to release a new version if we success.
