### ISSUE TITLE
Question on `running_prefix` Calculation with `kNRows > 1` in `selective_scan_fwd_kernel.cuh`

### ISSUE THREAD

**Issue by YouHuang67** [MzeroMiko/VMamba#42]
Hi,

I'm looking into the CUDA implementation in `selective_scan` and have a specific question about the handling of `running_prefix` in scenarios where `kNRows` exceeds 1. This is concerning the code snippet from `selective_scan/csrc/selective_scan
/selective_scan_fwd_kernel.cuh`:

```cuda
// Line 173
running_prefix = chunk > 0 && threadIdx.x % 32 == 0 ? smem_running_prefix[state_idx + r * Ktraits::MaxDState] : make_float2(1.f, 0.f);
```
As I understand it, `running_prefix` serves as the starting value for the current BlockScan. For cases where `chunk > 0` and `threadIdx.x % 32 == 0` (indicating every 32 threads as a warp for processing), it's necessary to load the previous final result `smem_running_prefix[state_idx + r * Ktraits::MaxDState]` as the new `running_prefix`. This implies that for iterations where `r > 0`, the computation should also consider the results from previous iterations.

Specifically, given that VMamba introduces an `nrows` parameter allowing for `kNRows` to be more than 1, I'm curious if overlooking the `r > 0` scenario could lead to issues. Should the code account for the cumulative effect of previous `r` iterations on `running_prefix` to ensure correct calculations? It's worth noting that in the original Mamba code, `kNRows` is fixed to 1, thus there is no consideration for iterations where `r > 0`.

Could you shed some light on whether my interpretation aligns with the intended logic of this implementation, or if there's an aspect I might be missing?

Thank you for your insight!

**Comment by MzeroMiko** [comment]
`kNRows` stands for the number of data one thread process in the dimention of `d_model` or `d_state`. There's no dependence between each data in different index in the dimension `d_model`, you can just treat it as `batch` all through the cuda kernel.

You can use `test_selective_scan.py` with different `nrows` to check whether this implementation is equal to the implementation of `mamba_ssm`.

The only consideration lies in `kNRows` is that is it really needed for raising the speed, or in what case, bigger `nrow` means faster code. And this is still under exploration.

**Comment by MzeroMiko** [comment]
By the way, I am glad that you are interested in the C source files of selective scan. You can check [mamba](https://github.com/state-spaces/mamba), [mamba-mini](https://github.com/MzeroMiko/mamba-mini), [mamba.py](https://github.com/alxndrTL/mamba.py) [mamba-minimal](https://github.com/johnma2006/mamba-minimal) for more information.

**Comment by YouHuang67** [comment]
> By the way, I am glad that you are interested in the C source files of selective scan. You can check [mamba](https://github.com/state-spaces/mamba), [mamba-mini](https://github.com/MzeroMiko/mamba-mini), [mamba.py](https://github.com/alxndrTL/mamba.py) [mamba-minimal](https://github.com/johnma2006/mamba-minimal) for more information.

Thank you so much for pointing me towards these resources! I believe that Mamba's CUDA implementation represents a crucial contribution, particularly due to its efficient iterative design that leverages CUDA's BlockScan for acceleration. This opens up fresh perspectives on designing structures for large models. It's a pity that the paper offers limited description on this aspect, leaving code as the primary means to grasp these concepts. I'm truly grateful for the information you've provided.
