### ISSUE TITLE
Pretrained weight of original Mamba

### ISSUE THREAD

**Issue by Jeff001128** [MzeroMiko/VMamba#44]
Hi, I'm doing an ablation study to compare the VMamba with the original Mamba. Although I know it's not obliged for you to provide the pretrained weight of the original Mamba, I would still like to inquire about the possibility for you to provide the pretrained weight of the original Mamba on image classification.

Thanks!

**Comment by MzeroMiko** [comment]
`Mamba` is not intended for image classification, and we did not test the performance of original mamba either. 
We do not have the pretrained weight of mamba as we trained `VMamba` from scratch.
