### ISSUE TITLE
Could you provide the code example about Effective Receptive Field (ERF) ?

### ISSUE THREAD

**Issue by ChiShengChen** [MzeroMiko/VMamba#48]
Hi, thanks for your awesome work! Could you provide the code about how to reproduce the Figure 5 in your paper?
I have not find the official code about the paper https://arxiv.org/pdf/1701.04128.pdf
Could you provide the related code if it is convenient？ Thanks a lot!

**Comment by MzeroMiko** [comment]
We draw the ERF figures with [get_erf.py](https://github.com/MzeroMiko/VMamba/blob/main/analyze/get_erf.py), which is mainly adopted from `RepLKNet`.

**Comment by ChiShengChen** [comment]
Thanks for quick reply, it helps alot!
