### ISSUE TITLE
Question About the VSSBlock

### ISSUE THREAD

**Issue by csguoh** [MzeroMiko/VMamba#5]
Hi, authors
Thanks for this incredible work! When I run the code in this repo, I have a question about the architechre of the VSSBlock.
In the code inplemantation, the VSSBlock is achieved by `x = input + self.drop_path(self.self_attention(self.ln_1(input)))` in [this line](https://github.com/MzeroMiko/VMamba/blob/9ca24aee4bbffdb34619151afe8aa7a6ca278e44/classification/models/vmamba/vmamba.py#L403). However, it seems that this implementation is not match with the Fig4(b) in the original paper, and it confuses me a lot. 

Thanks!

**Comment by sunsmarterjie** [comment]
Where is the mismatch?

**Comment by sunsmarterjie** [comment]
We integrated some operations of the VSS block into the SS2D block, and the implementation is the same.

**Comment by csguoh** [comment]
> We integrated some operations of the VSS block into the SS2D block, and the implementation is the same.

Thanks for your reply, I think it has solved my question!
