### ISSUE TITLE
Could you please provide the single function to test the params and flops in a single SS2D, which can be used to compare the complexity of different forward_...?

### ISSUE THREAD

**Issue by 924973292** [MzeroMiko/VMamba#50]
Thanks for your fast rely, hope to see the result!

**Comment by MzeroMiko** [comment]
we use `fvcore` to calculate params and flops, so there's no need for us to write the scripts to count flops individually.

Follow the [code](https://github.com/MzeroMiko/VMamba/blob/05849306028845f6a0034d29ffb523d21006fce1/classification/models/vmamba.py#L1020) and just run any module (for instance, SS2D) that you are interested in, like what you do with other models, and then you'll find the flops and params come out themselves.

**Comment by 924973292** [comment]
Thanks!!!
