### ISSUE TITLE
Pretrained checkpoint parameters loaded failed

### ISSUE THREAD

**Issue by mywebinfo65536** [MzeroMiko/VMamba#53]
Hello,  when I load the pretrained parameters of your small version checkpoint  from Classification on ImageNet-1K, there are many missing keys and unexcepted keys as blow picture showed:

![截图20240226162640](https://github.com/MzeroMiko/VMamba/assets/105631236/f045340c-5dc5-46d5-b73c-ee096b27a0d4)

Could you help to point out the problem ? thanks very much.

**Comment by MzeroMiko** [comment]
Have you deleted something in VSSM? 
There's a function called `_load_from_state_dict`, which is used to transfer the weight from previous pretrained models to this model. That should work when you call `load_state_dict`.

**Comment by mywebinfo65536** [comment]
oh yes, I commented out _load_from_state_dict function.  It is OK now. thanks.
