### ISSUE TITLE
Pytests fail with mamba_ssm_ssoflex, and questions

### ISSUE THREAD

**Issue by DianCh** [MzeroMiko/VMamba#57]
Hi, thank you for this wonderful repo. I'm playing with the latest `mamba_ssm_ssoflex` option, but the pytests all failed (the `mamba_ssm_sscore` can all pass). How can I make the ssoflex version match the sscore version?

```
E           TypeError: fwd(): incompatible function arguments. The following argument types are supported:
E               1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: torch.Tensor, arg4: torch.Tensor, arg5: Optional[torch.Tensor], arg6: Optional[torch.Tensor], arg7: bool, arg8: int) -> List[torch.Tensor]
```

While the speedup looks very appealing, I'm also wondering what performance you get with `mamba_ssm_ssoflex`, and if it hurts the performance or training stability - since the readme is updated with only memory & FPS. I'd appreciate any suggestions in using this `ssoflex` version.

**Comment by MzeroMiko** [comment]
Thank you for pointing that out.
You can change the code in line 348 and 350 from `selective_scan_cuda_core` to `selective_scan_cuda_oflex` to fix that.

Here is the [example](https://github.com/MzeroMiko/VMamba/blob/fd0edb6b69887a3e33fb3efac65e72f5893d52b8/selective_scan/test_selective_scan.py#L348).
