### ISSUE TITLE
Question about the scan order

### ISSUE THREAD

**Issue by eclipse0922** [MzeroMiko/VMamba#6]
Thank you for sharing great works
I have some questions about the scan order.
VMamaba has a global receive field, but patches in the horizontal vertical have a much stronger impact. This is despite the fact that other patches that are not in the horizontal vertical direction have shorter L2 distances.
![image](https://github.com/MzeroMiko/VMamba/assets/6214316/ff26f294-2cef-4f38-9986-a0b81dcf9186)

Looking at the figure, it appears that this is due to the scanning order. The patches in the horizontal vertical orientation are scanned last, although patches in other orientations also have an effect. The patches in different orientations are relatively far apart in terms of scanning order, although they obviously have shorter L2 distances.
 This is somewhat offset by the fact that they are scanned once in the vertical and once in the horizontal direction, as suggested in the paper.
![image](https://github.com/MzeroMiko/VMamba/assets/6214316/95fae751-75ef-4683-b3b0-33686215614b)

Is the  scanning order that used in the paper choosed for the better speed?

Have you tried other scan order(morton curve or cantor curve or something else)
![image](https://github.com/MzeroMiko/VMamba/assets/6214316/29243ecb-a438-42b5-921d-274b3a95ef5a)
image from https://www.researchgate.net/figure/Space-filling-curves_fig4_332651207

The hilbert curve seems to have a similar problem because of the scan order.

**Comment by sunsmarterjie** [comment]
Thank you for your interesting question. However, we haven't tried additional approaches yet. We are in the process of exploring, and if we achieve better results, we will keep everyone informed.

**Comment by eclipse0922** [comment]
@sunsmarterjie I appreciate you. I'm really looking forward to it.
