### ISSUE TITLE
Purpose of folder kernels/cross_scan

### ISSUE THREAD

**Issue by Kiet0712** [MzeroMiko/VMamba#75]
Hi, I found that in the last commit you have add a new folder that is kernels/cross_scan.
I don't really understand what is the purpose of this ? Can you explain for me about this ? (In my opinion I think that it will help SS2D run faster because of c++ code)
Thank you very much!

**Comment by MzeroMiko** [comment]
I did implement `CrossScan` and `CrossMerge` in Cuda, but with my poor skills in Cuda-writing, I succeeded in writing that part right but failed to speed up. So, I deleted that folder now.
Thanks to the `triton` repo, which enables Cuda-beginners to write Cuda-efficient code, I implemented the `CrossScan` and `CrossMerge` in triton now, which is 2x faster than before in that part.
You can check the `CrossScanTriton` with `check_csm_triton()` now.
