### ISSUE TITLE
Question about The History of Speed Up

### ISSUE THREAD

**Issue by Kiet0712** [MzeroMiko/VMamba#77]
Hi, thank you for continue in speed up everything but i have a question about the latest speed up.
When i change the config of forward type from v2 to v4, i found that it can run faster when inference which is very good, but the result is the speed of training is decrease.
Can you confirm for me something about the value in table The History of Speed Up that it is the time the model need in inference or in training time ?
Thank!

**Comment by MzeroMiko** [comment]
The time is tested under the training procedure in 1xA100 PCIE with batch size 128, we observed the 
 time in log at the first 100-200 iteration, and made a conclusion.
