### ISSUE TITLE
selective_scan_cuda_oflex.cpython-310-x86_64-linux-gnu.so: undefined symbol

### ISSUE THREAD

**Issue by MyLittleChange** [MzeroMiko/VMamba#83]
Hi, thanks for the amazing work.

I successfully install the selective-scan. But when I run ` pytest test_selective_scan.py`, I get the following error:

` ImportError while importing test module '/.. /training/VMamba/kernels/selective_scan/test_selective_scan.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../anaconda3/envs/vmamba/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_selective_scan.py:356: in <module>
    import selective_scan_cuda_oflex
E   ImportError: ./anaconda3/envs/vmamba/lib/python3.8/site-packages/selective_scan_cuda_oflex.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv`

I am using cuda 12.1 + python 3.10 + torch 2.2 on an A100 GPU.

I've tried several combinations of CUDA, Python, and PyTorch versions, but I'm still facing the same problem. Could you provide any insights on how to resolve this issue?

**Comment by TmkPjj** [comment]
I also meet the same problem.
