### ISSUE TITLE
Problem with Downloading Checkpoints for Certain Models

### ISSUE THREAD

**Issue by HashmatShadab** [MzeroMiko/VMamba#87]
I have encountered problems trying to download the checkpoints for the following models:

- VMamba-T(0229)
- VMamba-S
- VMamba-B

From the table provided in the readme, it appears that the provided links for these checkpoints are not functioning. I would appreciate it if someone could look into this issue and provide = working links.

Thank you for your attention to this matter. Your prompt response will be highly appreciated.

**Comment by MzeroMiko** [comment]
We have not released those models yet. We prepare to release them in weeks.

The very early version of models can be downloaded in github.

**Comment by HashmatShadab** [comment]
Thanks!
