### ISSUE TITLE
Confusion on the calculation of \overline{B}

### ISSUE THREAD

**Issue by lambdawill** [MzeroMiko/VMamba#98]
![图片](https://github.com/MzeroMiko/VMamba/assets/26055298/228411d9-a4b3-475d-9e7a-026ebdc524ec)
In [12]
![图片](https://github.com/MzeroMiko/VMamba/assets/26055298/5814222e-e5ca-4246-a75a-85ff653dc3ca)
Can you explain this ?, thank you!

**Comment by MzeroMiko** [comment]
It is a discretization with `zero order hold` method, and is adopted from mamba. You can check mamba for details. 

Here's my understanding:
1. first we can get the solution to the ODE as I did in [mamba-mini](https://github.com/MzeroMiko/mamba-mini) 
2. we adopt the ZOH hypothesis in the first one, which makes the B, C, A, u, stable from t_k to t_{k+1}, then we get A* = exp(A dt). 
3. As for the second one, also use ZOH: int_{t_a}^{t_b} {B_t * u_t * exp(-A dt) * dt} ~=  B_t * u_t  * int_{t_a}^{t_b} {exp(-A * t + A * t_a) * dt} = B_t * u_t  * int_{0}^{t_b - t_a} {exp(-A * t) * dt} = (exp(A (t_b - t_a)) - I) / A

But in practise, I would like to use the trivial discretization as I shows in mamba-mini.

I hope that helps.

**Comment by lambdawill** [comment]
From the integral software (three types), I just get the result like $$\frac{I-exp(-A (t_b - t_a))}{A}$$, and it does not equal to $$\frac{exp(A (t_b - t_a))-I}{A}$$. Or maybe  I miss something?

**Comment by MzeroMiko** [comment]
Sorry, you are right, and I missed the fator "exp(A (t_b - t_a))" before the integral. Then you will have the equation in second line.
