### ISSUE TITLE
Some questions about S6 block

### ISSUE THREAD

**Issue by lambdawill** [MzeroMiko/VMamba#99]
![图片](https://github.com/MzeroMiko/VMamba/assets/26055298/46f9807a-8a1b-4c46-8b1f-5cb78864b2bc)
1. Compared with [12], you additionally keep D in the output equation, does this will be better ? It seems, if we do not keep D, the calculation of $y_t$ will be more faster or not?
![图片](https://github.com/MzeroMiko/VMamba/assets/26055298/dfeb3dbb-f645-405d-a789-d1769d21f749)

2. I am not sure what's the relationship between $y_t$ and $y_L$.  Does it means:  for each patch $y_l$, we need to compute the patch state after $t$ iterations of linear-variant state changing? So, the scan order aims to let $\Delta$, $B$ and $C$ depending on the $x$. so for each patch, the state changing process depends on $x$.   Maybe I am wrong, it seems that SSM differs with diffusion (which needs to iterates $t$ times), here, in SSM, $t$ just represents the patch order?

**Comment by MzeroMiko** [comment]
1. If we do not keep D, the calculation will be faster. We did not test the performance change if we delete D.
2. $y_L$ means the output y with shape (B,G,D,L), $y_t$ is one of the output sequences in time t, with shape (B, G, D, 1)
